@startuml
'https://plantuml.com/class-diagram

interface UIComponent{
    + String show()
    + void add(UIcomponent ui)
    + void remove(UIcomponent ui)
}
UIComponent <|.. Layout
UIComponent <|.. Component
Layout *--> UIComponent:childen


note bottom of Layout
    Composite
end note

note bottom of Component
    Component
end note
@enduml